### PR TITLE
Make -test have the same behavior as with nunit

### PR DESCRIPTION
**Pull request by luhenry**

### CODE REVIEW

**Comment by akoeplinger** [comment]
I don't recall this being a feature with NUnit proper, was this something we hacked into our NUnit fork too?

**Comment by ludovic-henry** [comment]
When you use `make check -C mcs/class/corlib TESTNAME=System.Threading` for example, on nunit, you would have all TestFixture which namespace starts with `MonoTests.System.Threading` but with nunit-lite (without this patch), you wouldn't have any test run, because it doesn't match a TestFixture or a Test.

**Comment by akoeplinger** [comment]
It is implemented differently there though. `make check -C mcs/class/corlib TESTNAME=System.Threadi` doesn't run any tests with old NUnit (as expected).

**Comment by ludovic-henry** [comment]
Well it used to, as I was using that to try to run all tests in a specific namespace.

**Comment by akoeplinger** [comment]
It does that if you specify the full namespace, not a substring like we do it here :)
I can't find where the implementation of this lives in old NUnit, and I agree this is useful so let's just go with your solution.

Can you please wrap the changes in `#if MONO` though so we have an easier time merging upstream changes?

**Comment by ludovic-henry** [comment]
Currently, with nunit-lite, if you pass `make check -C mcs/class/corlib TESTNAME=System.Threading` no test will be run.

I will add the `#if MONO`

**Comment by akoeplinger** [comment]
> Currently, with nunit-lite, if you pass make check -C mcs/class/corlib TESTNAME=System.Threading no test will be run.

Yep. To clarify: I meant that NUnit didn't run tests if you do `TESTNAME=System.Threadi` which now works on nunitlite with your patch.

**Comment by ludovic-henry** [comment]
right

**Pull request merged**
